FROM selenium/standalone-firefox
# FROM seleniarm/standalone-firefox

USER root
RUN apt-get update && apt-get install python3-distutils -y
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
RUN python3 -m pip install selenium
# ENTRYPOINT /bin/bash

USER seluser
WORKDIR /home/seluser
ADD ./selenium/ /selenium
ADD ./docker/bootstrap.sh /bootstrap.sh
ENTRYPOINT /bootstrap.sh
# CMD /selenium/morizon.py
